- name: Install required packages
  ansible.builtin.package:
    name: "{{ apache_packages[ansible_facts['os_family']] }}"
    state: present

- name: Remove default index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Start and enable Apache (systemd)
  ansible.builtin.service:
    name: "{{ apache_service[ansible_facts['os_family']] }}"
    state: started
    enabled: yes
  when: ansible_service_mgr == 'systemd'

- name: Start Apache manually if no systemd (docker etc.)
  ansible.builtin.shell: apachectl -DFOREGROUND &
  args:
    creates: /var/run/httpd/httpd.pid
  when: ansible_service_mgr != 'systemd'

- name: Start MariaDB manually if no systemd
  ansible.builtin.shell: mysqld_safe --datadir=/var/lib/mysql &
  args:
    creates: /var/run/mysqld/mysqld.pid
  when: ansible_virtualization_type == "docker"

- name: Wait for MariaDB
  ansible.builtin.wait_for:
    port: 3306
    delay: 5
